### ISSUE TITLE
删除方法没有监测一对一关系?

### ISSUE THREAD

**Issue by wwkl** [scubers/JRDB#11]
jr_deleteOne只监测一对多关系，一对一不监测?

**Comment by scubers** [comment]
这里的一对一是指逻辑上的一对一，并非数据库上的一对一。
当AModel持有 ID为111的BModel  的同时， CModel也有可能持有 ID 为111 的BModel，虽然逻辑上一般不会出现这种情况，但是我们不能杜绝这种情况如果deleteOne Amodel的时候吧 持有的BModel删除了，Cmodel则出现数据错误的情况，所以deleteOne不进行一对一的删除检测。暂时没找到比较好的解决办法，如果有比较好的提案，麻烦提醒下~~
