### ISSUE TITLE
自身的一对多关系，保存错误

### ISSUE THREAD

**Issue by wwkl** [scubers/JRDB#12]
若AModel具有自身的一对多关系，调用save方法会报错
DB Error: 1 "duplicate column name: AModel_ids"
DB Query: create table if not exists AModel_AModel_Mid_Table (AModel_ids TEXT, AModel_ids TEXT)

**Comment by scubers** [comment]
非常感谢，这是个大bug，马上着手解决

**Comment by scubers** [comment]
已经解决同类一对多保存错误，~~非常感谢bug提供~~~
