### ISSUE TITLE
最新版本的自定义主键和键值有BUG

### ISSUE THREAD

**Issue by HuaZao** [scubers/JRDB#15]
#pragma mark - save one

/**
 *  保存单条，不关联保存
 */
- (BOOL)jr_saveOneOnly:(id<JRPersistent>)one {
    AssertRegisteredClazz([one class]);
    if ([[one class] jr_customPrimarykey]) { // 自定义主键
        NSAssert([one jr_customPrimarykeyValue] != nil, @"custom Primary key should not be nil");
//        NSObject *old = (NSObject *)[self jr_getByPrimaryKey:[one jr_customPrimarykeyValue] clazz:[one class]];
        NSAssert(![self jr_count4PrimaryKey:[one jr_customPrimarykeyValue] clazz:[one class]], @"primary key is exists");
    } else { // 默认主键
        NSAssert(one.ID == nil, @"The obj:%@ to be saved should not hold a ID", one);
    }
    
    JRSql *sql = [JRSqlGenerator sql4Insert:one toDB:self];
    [one setID:[JRUtils uuid]];
    [sql.args insertObject:one.ID atIndex:0];
    BOOL ret = [self jr_executeUpdate:sql];
    
    if (ret) {
        // 保存完，执行block
        [one jr_executeFinishBlocks];
    }
    return ret;
}

上面的代码有问题....无论如何都是保存了[JRUtils uuid]这个Value  还有[[one class] jr_customPrimarykey]调用了设置主键而不是设置主键的默认值......应该是[one jr_customPrimarykeyValue]吧...

最后改成这样就没问题了
/**
 *  保存单条，不关联保存
 */
- (BOOL)jr_saveOneOnly:(id<JRPersistent>)one {
    AssertRegisteredClazz([one class]);
    if ([one jr_customPrimarykeyValue]) { // 自定义主键
        NSAssert([one jr_customPrimarykeyValue] != nil, @"custom Primary key should not be nil");
//        NSObject *old = (NSObject *)[self jr_getByPrimaryKey:[one jr_customPrimarykeyValue] clazz:[one class]];
        NSAssert(![self jr_count4PrimaryKey:[one jr_customPrimarykeyValue] clazz:[one class]], @"primary key is exists");
        JRSql *sql = [JRSqlGenerator sql4Insert:one toDB:self];
        [one setID:[one jr_customPrimarykeyValue]];
        [sql.args insertObject:one.ID atIndex:0];
        BOOL ret = [self jr_executeUpdate:sql];
        
        if (ret) {
            // 保存完，执行block
            [one jr_executeFinishBlocks];
        }
        return ret;
    } else { // 默认主键
        NSAssert(one.ID == nil, @"The obj:%@ to be saved should not hold a ID", one);
        JRSql *sql = [JRSqlGenerator sql4Insert:one toDB:self];
        [one setID:[JRUtils uuid]];
        [sql.args insertObject:one.ID atIndex:0];
        BOOL ret = [self jr_executeUpdate:sql];
        
        if (ret) {
            // 保存完，执行block
            [one jr_executeFinishBlocks];
        }
        return ret;
    }
}

不知道理解有没有问题....还是我的写法有问题

**Comment by scubers** [comment]
能否给出你实际出现bug的代码呢
