### ISSUE TITLE
只能支持ios8以上的系统吗？

### ISSUE THREAD

**Issue by lieu-woxinxiangni** [scubers/JRDB#16]
如果我把源码下载下来，将@import改成＃import是否就可以支持ios7了？

**Comment by scubers** [comment]
可以的，因为不还不大熟悉cocoapods，里面有些依赖还没搞懂，就直接用framework了，可以把源码下下来，然后自己导入fmdb，改一下头文件就可以了

**Comment by scubers** [comment]
如果使用过程中，出现什么bug，可以联系我修改，马上说马上改😉
