### ISSUE TITLE
自定义主键模型采用带complete的保存方法，保存完成后会有ResultSet未释放

### ISSUE THREAD

**Issue by wwkl** [scubers/JRDB#20]
保存完成后FMDB会警告Warning: there is at least one open result set around after performing [FMDatabaseQueue inDatabase:]，貌似是jr_saveOneOnly这里有点问题
NSAssert(![self jr_count4PrimaryKey:[one jr_customPrimarykeyValue] clazz:[one class]], @"primary key is exists");

**Comment by scubers** [comment]
正在查找问题，方便贴一下出问题的代码吗？我的qq ： 492956098，有问题直接告诉我，这样我修复得快点~~~谢谢啦~~~

**Comment by scubers** [comment]
无法重现问题~~，但是添加了释放resultset的代码
