### ISSUE TITLE
readme写得看不太明白

### ISSUE THREAD

**Issue by GitterYang** [scubers/JRDB#22]
如果我用最新版本，旧版本下面的都不用看了吗？readme中英文混合，看着有点别扭

**Comment by scubers** [comment]
给你造成困扰非常抱歉，因为更新频率比较高，readme不一定更得上，待框架稳定了，将出一份比较完整的readme。现阶段，readme上看到的都是可以用的，旧版本有些api不支持，推荐使用最新版本。

**Comment by GitterYang** [comment]
旧版本的使用可以使用引用地址，不要出现在readme中， 不然看着真是好混乱，每个人在使用前都会去看下是否简介，是否好用，是否适合自己的业务，麻烦了。
