### ISSUE TITLE
主键问题

### ISSUE THREAD

**Issue by hzw598** [scubers/JRDB#24]
当我设置jr_customPrimarykey为userId后，发现创建表语句并没有按照预期的进行，JRDB仍然创建了ID字段并设置其为主键。打印语句如下：CREATE TABLE User (_ID text primary key , _name TEXT, _age INTEGER, _birthday TIMESTAMP, _userId INTEGER, _size INTEGER)

**Comment by scubers** [comment]
你好，创建表的时候都是使用_ID作为主键的。代码上设置的为逻辑主键，在增删改查的时候，代码会逻辑判断使用逻辑逐渐进行操作。
