### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by hzw598** [scubers/JRDB#25]
由于Sqlite支持自增长主键，我觉得主键ID可以设置为自增长主键，这样设置，排序查询会快很多。创建表语句可改为：create table if not exists xxx (_ID INTEGER primary key autoincrement)

**Comment by scubers** [comment]
现在库还没开发到数据迁移，对应到以后数据迁移。如果使用自动增长怕会影响后期数据迁移引申的问题。所以采用了uuid进行设置主键。此_ID没有任何意义，所以排序的时候应该使用自己表内具有实际意义的字段进行排序~~。如果有什么说到不到位的地方，麻烦继续指出，持续改正。

**Comment by hzw598** [comment]
大牛，我是菜鸟，叨扰您了。我只是考虑到即时通讯开发本地化时，如果将两条或多条时间几乎无差别的聊天信息写入sqlite时，我该如何排序查询拿到这两条信息的先后顺序？我初步的想法是使用自增长主键来本地化写入，查询时再以倒序拿到两条消息的先后顺序，而且自增长主键查询速度应该比较快。以上是我的观点，还请大牛点拨一二。

**Comment by scubers** [comment]
插入的时候，添加一个字段，createTime，按照这个日期来排序即可
