### ISSUE TITLE
数据库不支持int64的数据类型吗？

### ISSUE THREAD

**Issue by wshugongxi** [scubers/JRDB#28]
我的主键是int64的数据类型，我插入时成功了，但查出来的数据_musicId的值全部是 0  这个是怎么回事呀？

`#ifndef _INT64_T
#define _INT64_T
typedef	long long		int64_t;
#endif /* _INT64_T */

@property(nonatomic,assign) int64_t musicId;                //歌曲id

#pragma - mark JRDB

+ (NSString *)jr_customPrimarykey
{
    return @"_musicId";
}

//主键的值
- (id)jr_customPrimarykeyValue
{
    return @(self.musicId);
}`

**Comment by scubers** [comment]
当时没考虑到，可以采用long进行替换

**Comment by wshugongxi** [comment]
希望后续版本可以支持，修改一个类型，相关读取的地方都得修改，是在太多了。。。

**Comment by scubers** [comment]
工作之余我尽量改~
开源的好处就是谁都可以改代码并且提交，期待您的贡献~~~
