### ISSUE TITLE
Property name被重构？

### ISSUE THREAD

**Issue by spemagic** [scubers/JRDB#3]
model某个property name被refactor了怎么办？好像FMResultSet查出来的结果集无法映射到model上了。

**Comment by scubers** [comment]
请问您是如何进行重构了？能否给出代码？
另外，现在的版本还不能对数据库字段和model属性进行映射（也就是说数据库字段名就是model的property属性全名），在后期会更新。

**Comment by spemagic** [comment]
比如说person原来的某个属性name，因为某些原因被重构成name1了，那后面该字段就无法正确赋值到model上了，也就是说表的某个字段和model的属性名无法一一对应

**Comment by scubers** [comment]
因为这个库是运用runtime进行字段名和属性名映射的，所以无法更改字段名。
后续提供字段名和属性名进行映射，还请关注后续更新，TOT，谢谢支持

**Comment by spemagic** [comment]
另外还需要支持protocol中的属性名，实际项目中可能会经常用。
btw，代码写的不错，加油！

**Comment by scubers** [comment]
其实protocol中的@property 只是一个声明作用（对应的Setter和Getter），并不是生成一个属性字段，所以在运行时无法得知对应的属性是什么名字。
这个的确有可能用到，会考虑解决方案。
~~~~
