### ISSUE TITLE
使用j_select

### ISSUE THREAD

**Issue by feimatayan** [scubers/JRDB#30]
J_Select([NoteSqlModel class]);
报错，不支持c99

**Comment by feimatayan** [comment]
<img width="986" alt="2016-12-06 6 41 55" src="https://cloud.githubusercontent.com/assets/10916484/20922133/0b475298-bbe2-11e6-8d41-89114c274a41.png">

**Comment by KONGFANJI** [comment]
去掉class

**Comment by scubers** [comment]
J_Select 是一个宏正确使用 J_Select(NoteSqlModel)即可，关于宏，可以点击链接进去查看展开
