### ISSUE TITLE
最好提供多表支持

### ISSUE THREAD

**Issue by 0xShaun** [scubers/JRDB#4]
对于项目中的多用户支持,每个用户对应一个同种类但是名字不同的表, ToDoListTable_liLei, ToDoListTable_wangMeiMei

**Comment by scubers** [comment]
好的，您的意见小弟会研究采纳
您说的需求表的功能都一样，为什么要分成两张表呢，用一个用户ID就可以区别了，如果是需要严格区分用户的，可以每个用户一个数据库，这样逻辑操作也不回混乱~~

**Comment by 0xShaun** [comment]
issue的目的不是这个需求, 而是支持多表, 让我知道我的数据存储在哪儿了, 使用数据库的人肯定都知道基本的,数据库-表 ,这个结构, 
当然需求的实现有很多种, 我这个需求示例是说,切换用户保留缓存, 我觉得多表操作会更好, ToDoListTable_%@,user.id  ,我只需要维护一套数据库, 切换用户的时候根据变量找对应的表. 逻辑完全不动

**Comment by scubers** [comment]
库的目的就是简化和屏蔽数据库操作，使用的时候不需要知道实际存储的位置和结构，就像CoreData，也无法得知内部操作原理。

另外同一表结构对应多张表的实现方案也在规划中~~，希望之后的更新中能给你提供更好的帮助

**Comment by 0xShaun** [comment]
🐎  感谢开源
