### ISSUE TITLE
请问如何设置联合主键

### ISSUE THREAD

**Issue by johann-wang** [scubers/JRDB#43]
1>请问如何取消默认的主键_ID.根据你提供的替换主键的方法+ (NSString *)jr_customPrimarykey {
    return @"userId";
}
- (id)jr_customPrimarykeyValue {
    return self.userId;
}
其中userid是字符串类型.这样还是原有的_ID主键
2>如果需要设置两个主键,请问怎么设置?

**Comment by scubers** [comment]
Sorry，本库尚不支持联合主键。
