### ISSUE TITLE
一个模型生成多张表的问题

### ISSUE THREAD

**Issue by ziyoufei** [scubers/JRDB#6]
我看了源码，写的很不错，我这里遇到一个问题就是一个模型只能生成一张表，而不能生成多张表，或者自定义表名，不知道你有没有好的解决方案

**Comment by scubers** [comment]
这个库的初衷就是屏蔽程序员和数据库之间打交道的过程，只用模型来操作数据库。
现阶段只是一个类对应一张表不能自定义表名和字段。
下阶段是更新关联保存和查询。
之后会考虑同一个类结构生成多张表的方案，暂时还没开始实施~~
如果您有好的方案，还请麻烦提醒下~~
