### ISSUE TITLE
XCode12 JRDB编译报错

### ISSUE THREAD

**Issue by jiabin87428** [scubers/JRDB#61]
Incompatible block pointer types sending 'id  _Nullable (^)(id<JRPersistentHandler>  _Nonnull __strong)' to parameter of type 'id  _Nullable (^ _Nonnull)(id<JRPersistentBaseHandler>  _Nonnull __strong)'

**Comment by hantu123** [comment]
i have the same question

**Comment by scubers** [comment]
please checkout branch "fix/xcode12", and try

**Comment by scubers** [comment]
try pod "JRDB", :git => 'https://github.com/scubers/JRDB.git', :branch => 'fix/xcode12_compile'

**Comment by scubers** [comment]
try
pod "JRDB", :git => 'https://github.com/scubers/JRDB.git', :branch => 'fix/xcode12_compile'

**Comment by hantu123** [comment]
大佬你好：

已测试编译通过

环境：xcode12，ios14.0



在 2020-09-17 19:43:03，"jrw0ng" <notifications@github.com> 写道：

try
pod "JRDB", :git => 'https://github.com/scubers/JRDB.git', :branch => 'fix/xcode12_compile'

**Comment by jiabin87428** [comment]
> try
> pod "JRDB", :git => 'https://github.com/scubers/JRDB.git', :branch => 'fix/xcode12_compile'

Thanks
